# Generated by Django 2.1.1 on 2018-09-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleveiculos', '0003_seguro'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguro',
            name='apólice',
            field=models.IntegerField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seguro',
            name='valor',
            field=models.IntegerField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
