# Generated by Django 2.1.1 on 2018-09-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleveiculos', '0004_auto_20180928_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguro',
            name='seguradora',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
