# Generated by Django 2.1.1 on 2018-09-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleveiculos', '0005_seguro_seguradora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguro',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
