# Generated by Django 2.1.1 on 2018-09-28 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controleveiculos', '0006_auto_20180928_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='pertence',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='controleveiculos.Casa'),
            preserve_default=False,
        ),
    ]
