# Generated by Django 2.1.1 on 2018-09-28 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controleveiculos', '0009_auto_20180928_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='marca',
        ),
        migrations.AddField(
            model_name='veiculo',
            name='marca_veiculo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='controleveiculos.Marca'),
            preserve_default=False,
        ),
    ]
