# Generated by Django 2.1.1 on 2018-09-28 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controleveiculos', '0010_auto_20180928_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detran', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='dentran',
        ),
        migrations.AddField(
            model_name='veiculo',
            name='detran',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='controleveiculos.Detran'),
            preserve_default=False,
        ),
    ]
