# Generated by Django 2.1.1 on 2018-10-02 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controleveiculos', '0011_auto_20180928_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='pertence_a',
        ),
        migrations.AddField(
            model_name='veiculo',
            name='casa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='controleveiculos.Casa', verbose_name='pertence a'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='chassi',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='documento',
            field=models.CharField(max_length=2),
        ),
    ]
